<?php

/**
 * @file
 * Contains hook implementations for the Ascend AP module.
 */

use Drupal\ascend_ap\Hook\ApHooks;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\LegacyHook;
use Drupal\Core\Render\Element;

/**
 * Legacy hook implementation.
 *
 * @todo Remove this method when support for Drupal core < 11.1 is dropped.
 */
#[LegacyHook]
function ascend_ap_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service(ApHooks::class)->formAlter($form, $form_state, $form_id);
}

/**
 * Legacy hook implementation.
 *
 * @todo Remove this method when support for Drupal core < 11.1 is dropped.
 */
// #[LegacyHook]
// function ascend_ap_config_pages_insert(EntityInterface $entity) {
//   \Drupal::service(ApHooks::class)->configPagesInsert($entity);
// }

/**
 * Legacy hook implementation.
 *
 * @todo Remove this method when support for Drupal core < 11.1 is dropped.
 */
// #[LegacyHook]
// function ascend_ap_config_pages_update(EntityInterface $entity) {
//   \Drupal::service(ApHooks::class)->configPagesUpdate($entity);
// }

/**
 * Legacy hook implementation.
 *
 * @todo Remove this method when support for Drupal core < 11.1 is dropped.
 */
// #[LegacyHook]
// function ascend_ap_entity_type_alter(array &$entity_types) {
//   \Drupal::service(ApHooks::class)->userAlter($entity_types);
// }

/**
 * These two functions were required in order to add compatibility with
 *  field_group module. This also necessitated the audit.html.twig template.
 *  https://www.drupal.org/project/field_group/issues/2859858
 */

function ascend_ap_theme($existing, $type, $theme, $path) {
  return [
    // This is for the field_group workaround above`.
    'ap' => [
      'render element' => 'elements',
    ],
  ];
}

function template_preprocess_ap(&$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];

  // Helpful $content variable for templates.
  $variables += ['content' => []];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

// Get AP entity edit forms handled by gin (to get sidebar).
function ascend_ap_gin_content_form_routes(): array {
  return [
    'entity.ap.add_form',
    'entity.ap.edit_form',
    'entity.ap.add_form.auditor',
    'entity.ap.edit_form.auditor'
  ];
}
